services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=auth_service_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - auth_notification_network

  auth-service:
    build: .
    container_name: auth-service
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - auth_notification_network

networks:
  auth_notification_network:
    external: true

volumes:
  postgres_data: